/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewApplet.java
 *
 * Created on Dec 19, 2011, 2:49:48 PM
 */
package RecipeWriter;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;

/**
 *
 * @author tjen
 */
public class RecipeWriterApplet_SaveAble extends java.applet.Applet {

    /** Initializes the applet NewApplet */
    @Override
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {

                @Override
                public void run() {
                    initComponents();
                    recipePanel1.addSaveNotifier(new SaveHandler());
                }
            });
        } catch (Exception ex) {
        }
        this.setSize(490, 800);
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jFileChooser1 = new javax.swing.JFileChooser();
        recipePanel1 = new RecipeWriter.RecipePanel();

        setLayout(new java.awt.BorderLayout());

        jFileChooser1.setAcceptAllFileFilterUsed(false);
        jFileChooser1.setCurrentDirectory(null);
        jFileChooser1.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        jFileChooser1.setSelectedFile(new java.io.File("C:\\Program Files\\NetBeans 7.0.1\\*.xml"));
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileSelectionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jFileChooser1, java.awt.BorderLayout.CENTER);

        jInternalFrame1.setBounds(10, 10, 470, 400);
        jLayeredPane1.add(jInternalFrame1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        recipePanel1.setBounds(10, 10, 477, 897);
        jLayeredPane1.add(recipePanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        add(jLayeredPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void fileSelectionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileSelectionPerformed

        File selectedFile = jFileChooser1.getSelectedFile();
        jInternalFrame1.setVisible(false);
        recipePanel1.saveToFile(selectedFile);
    }//GEN-LAST:event_fileSelectionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private RecipeWriter.RecipePanel recipePanel1;
    // End of variables declaration//GEN-END:variables

    class SaveHandler implements SaveAble {

        @Override
        public void save() {
            jInternalFrame1.setVisible(true);
        }
    }
}
