/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RecipePanel.java
 *
 * Created on Dec 13, 2011, 11:08:55 AM
 */
package RecipeWriter;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author tjen
 */
public class RecipePanel extends javax.swing.JPanel implements RecipeGetI, RecipeSetI {

    Model model;
    ArrayList<Recipe> recepten;
    DefaultListModel listModel;

    /** Creates new form RecipePanel */
    public RecipePanel() {
        initComponents();
        model = new Model();
        this.recepten = new ArrayList<Recipe>();
        this.listModel = new DefaultListModel();
        for (String recipeTitle : model.getRecipeTitles()) {
            this.listModel.addElement(recipeTitle);
        }
        this.listCurrentRecipes.setModel(listModel);
    }

    public void setActiveRecipe(RecipeGetI recipe) {
        txtComments.setText(recipe.getComments());
        txtIngredients.setText(recipe.getIngredients());
        txtInstructions.setText(recipe.getInstructions());
        txtPrepTime.setText(recipe.getPrepTime());
        txtCookTime.setText(recipe.getCookTime());
        txtQuantity.setText(recipe.getQuantity());
        txtTitel.setText(recipe.getRecipeTitle());
        txtUrl.setText(recipe.getUrl());
    }

    private void clear() {
        txtComments.setText("");
        txtIngredients.setText("");
        txtInstructions.setText("");
        txtPrepTime.setText("");
        txtCookTime.setText("");
        txtQuantity.setText("");
        txtTitel.setText("");
        txtUrl.setText("");
    }

    private Recipe makeRecipe() {
        return new Recipe(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTitel = new javax.swing.JTextField();
        lblTitel = new javax.swing.JLabel();
        lblBereidingsTijd = new javax.swing.JLabel();
        lblKookTijd = new javax.swing.JLabel();
        lblOpbrengst = new javax.swing.JLabel();
        lblIngredients = new javax.swing.JLabel();
        lblInstructions = new javax.swing.JLabel();
        lblComments = new javax.swing.JLabel();
        lblUrl = new javax.swing.JLabel();
        txtPrepTime = new javax.swing.JTextField();
        txtCookTime = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        txtUrl = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtIngredients = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtInstructions = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtComments = new javax.swing.JTextArea();
        btnExport = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnEmpty = new javax.swing.JButton();
        lblCurrentrecipes = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtXml = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        listCurrentRecipes = new javax.swing.JList();
        btnDelete = new javax.swing.JButton();
        lblXml = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        lblTitel.setText("Title:");

        lblBereidingsTijd.setText("Prep time:");

        lblKookTijd.setText("Cook time:");

        lblOpbrengst.setText("Quantity: ");

        lblIngredients.setText("Ingredients:");

        lblInstructions.setText("Instructions:");

        lblComments.setText("Comments:");

        lblUrl.setText("Url:");

        txtIngredients.setColumns(20);
        txtIngredients.setRows(5);
        jScrollPane1.setViewportView(txtIngredients);

        txtInstructions.setColumns(20);
        txtInstructions.setRows(5);
        jScrollPane2.setViewportView(txtInstructions);

        txtComments.setColumns(20);
        txtComments.setRows(5);
        jScrollPane3.setViewportView(txtComments);

        btnExport.setText("Show xml");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEmpty.setText("Clear");
        btnEmpty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmptyActionPerformed(evt);
            }
        });

        lblCurrentrecipes.setText("Current recipes:");

        txtXml.setColumns(20);
        txtXml.setRows(5);
        jScrollPane5.setViewportView(txtXml);

        jScrollPane4.setViewportView(listCurrentRecipes);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblXml.setText("Xml:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 686, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
                        .addComponent(lblInstructions)
                        .addComponent(lblComments)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblUrl)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtUrl, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnEmpty))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCurrentrecipes)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnDelete))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(26, 26, 26)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                                        .addComponent(lblXml, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnExport)
                                    .addGap(175, 175, 175))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblKookTijd)
                                .addComponent(lblOpbrengst)
                                .addComponent(lblIngredients)
                                .addComponent(lblBereidingsTijd)
                                .addComponent(lblTitel))
                            .addGap(22, 22, 22)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPrepTime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                                .addComponent(txtQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                                .addComponent(txtCookTime, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                                .addComponent(txtTitel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 837, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTitel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTitel))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPrepTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblBereidingsTijd))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCookTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblKookTijd))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblOpbrengst))
                    .addGap(13, 13, 13)
                    .addComponent(lblIngredients)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lblInstructions)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lblComments)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblUrl))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAdd)
                        .addComponent(btnEmpty))
                    .addGap(2, 2, 2)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCurrentrecipes)
                        .addComponent(lblXml))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDelete)
                        .addComponent(btnExport))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        Recipe recept = makeRecipe();
        String recipeTitle = recept.getRecipeTitle();
        model.addRecipe(recept);
        if (!listModel.contains(recipeTitle)) {
            listModel.addElement(recipeTitle);
            System.out.println("" + recipeTitle);
        } else {
            System.out.println("recipe " + recipeTitle + " edited");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEmptyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmptyActionPerformed
        clear();
    }//GEN-LAST:event_btnEmptyActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        List selectedRecipes = listCurrentRecipes.getSelectedValuesList();
        for (Object object : selectedRecipes) {
            if (object instanceof String) {
                String recipeTitle = ((String) object);
                model.removeRecipe(recipeTitle);
                listModel.removeElement(object);
            } else {
                System.out.println("Error");
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        txtXml.setText(model.getXml());
    }//GEN-LAST:event_btnExportActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEmpty;
    private javax.swing.JButton btnExport;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblBereidingsTijd;
    private javax.swing.JLabel lblComments;
    private javax.swing.JLabel lblCurrentrecipes;
    private javax.swing.JLabel lblIngredients;
    private javax.swing.JLabel lblInstructions;
    private javax.swing.JLabel lblKookTijd;
    private javax.swing.JLabel lblOpbrengst;
    private javax.swing.JLabel lblTitel;
    private javax.swing.JLabel lblUrl;
    private javax.swing.JLabel lblXml;
    private javax.swing.JList listCurrentRecipes;
    private javax.swing.JTextArea txtComments;
    private javax.swing.JTextField txtCookTime;
    private javax.swing.JTextArea txtIngredients;
    private javax.swing.JTextArea txtInstructions;
    private javax.swing.JTextField txtPrepTime;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtTitel;
    private javax.swing.JTextField txtUrl;
    private javax.swing.JTextArea txtXml;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getRecipeTitle() {
        return txtTitel.getText();
    }

    @Override
    public String getPrepTime() {
        return txtPrepTime.getText();
    }

    @Override
    public String getCookTime() {
        return txtCookTime.getText();
    }

    @Override
    public String getQuantity() {
        return txtQuantity.getText();
    }

    @Override
    public String getIngredients() {
        return txtIngredients.getText();
    }

    @Override
    public String getInstructions() {
        return txtInstructions.getText();
    }

    @Override
    public String getComments() {
        return txtComments.getText();
    }

    @Override
    public String getUrl() {
        return txtUrl.getText();
    }

    @Override
    public void setRecipeTitle(String recipeTitle) {
        txtTitel.setText(recipeTitle);
    }

    @Override
    public void setPrepTime(String prepTime) {
        txtPrepTime.setText(prepTime);
    }

    @Override
    public void setCookTime(String cookTime) {
        txtCookTime.setText(cookTime);
    }

    @Override
    public void setQuantity(String quantity) {
        txtQuantity.setText(quantity);
    }

    @Override
    public void setIngredients(String ingredients) {
        txtIngredients.setText(ingredients);
    }

    @Override
    public void setInstructions(String instructions) {
        txtInstructions.setText(instructions);
    }

    @Override
    public void setComments(String comments) {
        txtComments.setText(comments);
    }

    @Override
    public void setUrl(String url) {
        txtUrl.setText(url);
    }
}
